# Використовуємо офіційний образ PHP з Apache
# FROM node:22.14.0

# # Копіюємо фронтенд файли до контейнера
# COPY . ./

# # Встановлюємо необхідні розширення PHP для роботи з MySQL
# RUN npm install -g yarn
# RUN yarn install
# RUN yarn front-start

# # Вказуємо front слухати на порту 8080
# EXPOSE 8080

# CMD ["yarn", "front-start"]